from app.rag.lexical_retriever import (
    LexicalRetriever,
)
from app.rag.models import DocumentChunk


class FakeVectorStore:
    def __init__(
        self,
        chunks: list[DocumentChunk],
    ):
        self.chunks = chunks

    def get_chunks(
        self,
        where=None,
    ):
        return self.chunks


def _chunk(
    text: str,
    document: str,
    page: int,
    chunk_index: int,
) -> DocumentChunk:
    return DocumentChunk(
        text=text,
        document=document,
        page=page,
        chunk_index=chunk_index,
        ticker="AAPL",
        fiscal_year=2025,
    )


def test_lexical_retriever_prefers_exact_terms():
    vector_store = FakeVectorStore(
        [
            _chunk(
                text=(
                    "Operating income "
                    "was 133,050"
                ),
                document="a.pdf",
                page=1,
                chunk_index=0,
            ),
            _chunk(
                text=(
                    "Operating activities "
                    "generated cash"
                ),
                document="a.pdf",
                page=2,
                chunk_index=0,
            ),
            _chunk(
                text=(
                    "Revenue increased "
                    "during 2025"
                ),
                document="a.pdf",
                page=3,
                chunk_index=0,
            ),
            _chunk(
                text=(
                    "Research and development "
                    "expenses increased"
                ),
                document="a.pdf",
                page=4,
                chunk_index=0,
            ),
            _chunk(
                text=(
                    "Cash and cash equivalents "
                    "remained stable"
                ),
                document="a.pdf",
                page=5,
                chunk_index=0,
            ),
        ]
    )

    retriever = LexicalRetriever(
        vector_store=vector_store,
    )

    results = retriever.retrieve(
        query="operating income",
        top_k=2,
    )

    assert len(results) == 2

    assert results[0].page == 1

    assert (
        "Operating income"
        in results[0].text
    )

    assert results[1].page == 2

def test_lexical_retriever_respects_top_k():
    vector_store = FakeVectorStore(
        [
            _chunk(
                text=(
                    "Operating income "
                    "was 133,050"
                ),
                document="a.pdf",
                page=1,
                chunk_index=0,
            ),
            _chunk(
                text=(
                    "Operating income "
                    "increased during 2025"
                ),
                document="a.pdf",
                page=2,
                chunk_index=0,
            ),
            _chunk(
                text=(
                    "Net income "
                    "was 112,010"
                ),
                document="a.pdf",
                page=3,
                chunk_index=0,
            ),
        ]
    )

    retriever = LexicalRetriever(
        vector_store=vector_store,
    )

    results = retriever.retrieve(
        query="operating income",
        top_k=2,
    )

    assert len(results) == 2


def test_lexical_retriever_returns_empty_for_no_match():
    vector_store = FakeVectorStore(
        [
            _chunk(
                text=(
                    "Revenue increased "
                    "during the year"
                ),
                document="a.pdf",
                page=1,
                chunk_index=0,
            ),
            _chunk(
                text=(
                    "Cash generated by "
                    "investing activities"
                ),
                document="a.pdf",
                page=2,
                chunk_index=0,
            ),
        ]
    )

    retriever = LexicalRetriever(
        vector_store=vector_store,
    )

    results = retriever.retrieve(
        query="completely unrelated phrase",
        top_k=5,
    )

    assert results == []


def test_lexical_retriever_returns_empty_for_empty_query():
    vector_store = FakeVectorStore(
        [
            _chunk(
                text=(
                    "Operating income "
                    "was 133,050"
                ),
                document="a.pdf",
                page=1,
                chunk_index=0,
            ),
        ]
    )

    retriever = LexicalRetriever(
        vector_store=vector_store,
    )

    results = retriever.retrieve(
        query="   ",
        top_k=5,
    )

    assert results == []